version: "3"

services:
  php:
    image: php-phalcon-swoole:0.1
    container_name: php
    restart: always
    volumes:
      - /data/www:/data/www
      - /data/log/php:/var/log/php
  nginx:
    image: nginx:1.12
    container_name: nginx
    restart: always
    volumes:
      - /data/www:/data/www
      - /data/log/nginx:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: I9l70NXgkb
    volumes:
      - /data/mysql:/var/lib/mysql
      - /data/log/mysql:/var/log/mysql
      - ./mysql/conf.d/:/etc/mysql/conf.d
    ports:
      - "3306:3306"
  redis:
    image: redis:4-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"