version: "3"

services:
  mysql:
    image: mysql:5.7.41
    platform: linux/x86_64
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/conf.d/:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    networks:
      - develop-env

  redis:
    image: redis:6.2
    container_name: redis
    volumes:
      - ./redis/conf.d:/etc/redis
    ports:
      - "6379:6379"
    networks:
      - develop-env

  elasticsearch:
    image: elasticsearch:8.6.1
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - develop-env

  kibana:
    image: kibana:8.6.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
        - elasticsearch
    networks:
      - develop-env

networks:
  develop-env: